## Configuration files responsible for formating the command output, We need to search for the type of object generated by each command in the below files;
#We should not modify
notepad c:\Windows\System32\WindowsPowerShell\v1.0\DotNetTypes.format.ps1xml

#Identify the Type of Process Object and search it in the DotNetTypes.format.ps1xml

Notepad C:\Windows\System32\WindowsPowerShell\v1.0\types.ps1xml

#Identify the type of Output generated by get-wmiobject Win32_operatingsystem and search it in the types.ps1xml
System.ServiceProcess.ServiceController
Get-Service | Get-Member

System.diagnostics.process
Get-Process | Get-Member

Get-EventLog -LogName Application| Get-Member

#overriding the existing formating system.
Get-Service -Name BITS | Select-Object -Property Name, Status, StartType, DisplayName | 
                ConvertTo-Html -Head "<H1>Output for Bits Service</H1>" | Out-File C:\Users\Supercoach\Desktop\Services.html

Get-Process -Name notepad | Select-Object -Property Name, VM, PM, CPU


#Using Custom Formatting System
$a = "<style>"
$a = $a + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
$a = $a + "TH{border-width: 1px;padding: 10px;border-style: solid;border-color: black;background-color: #6495ED;}"
$a = $a + "TD{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "</style>"

Help convertto-html

Get-Process | Sort-Object -Property PM -Descending|select `
            @{Name ="Processname"; Expression={$_.Name}},`
            @{Name ="VM (MB)"; Expression={$_.vm/1MB -as [int]}},`
            @{Name ="PM (MB)"; Expression={$_.Pm/1MB -as [int]}},NPM -First 10 | 
            ConvertTo-Html -Title "Highest PM Consuiming Processes"  -Body $a | Out-file C:\Users\Supercoach\Desktop\process..html

## Just in case if you want to show the values in decimal points 
Get-Process | Sort CPU -Descending |Select-Object ProcessName,@{l='cpu';e={[math]::Round($_.cpu,3)}}

@{Name ="PM (MB)"; Expression={$_.Pm/1MB -as [int]}}
@{N ="PM (MB)"; E={$_.Pm/1MB -as [int]}}
@{Label="PM (MB)"; E={$_.Pm/1MB -as [int]}}
@{Name ="Processname"; Expression={$_.Name}}

$a = "<style>"
$a = $a + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
$a = $a + "TH{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "TD{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "</style>"

Get-WmiObject Win32_logicaldisk | where {$_.drivetype -eq 3} | 
                    Select-Object @{Name ="Drivename"; E={$_.DeviceID}},
                    @{Label ="FreeSize"; Expression ={$_.freespace/1GB -as [int]}},
                    @{Name ="TotalSize"; E ={$_.Size/1GB -as [int]}},
                    @{Name ="%Free"; E ={($_.freespace/$_.Size) * 100 -as [int]}} | 
                    ConvertTo-Html -Head "<H2> Diskspace Report<H2>" -Body $a | out-file C:\Users\Supercoach\Desktop\diskspace.htm


<#
$a = "<style>"
$a = $a + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
$a = $a + "TH{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "TD{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "</style>"
#>
[math]::Round($_.cpu,3)



$a = "<style>"
$a = $a + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
$a = $a + "TH{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "TD{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "</style>"

Get-Process | 
    Select @{Name='WS';Expression={$_.WorkingSet/1MB -as [int]}},
            @{Name='VMS64';Expression={$_.VirtualMemorySize64/1GB -as [int]}},
            @{Name='PVMS64';Expression={$_.PeakVirtualMemorySize64/1GB -as [int]}},
            @{Name='PPMS';Expression={$_.PeakPagedMemorySize/1MB -as [int]}},
            @{Name='PVMS';Expression={$_.PeakVirtualMemorySize/1MB -as [int]}} |
            Sort-Object -Property PVMS -Descending|
            ConvertTo-Html -Body $A| Out-File C:\Users\Supercoach\Desktop\test.html